# CI Workflow Contract
# Defines the interface and behavior of the CI testing workflow

workflow:
  name: CI
  file: .github/workflows/ci.yml
  purpose: Run automated tests, linting, and type checking on pull requests

triggers:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

permissions:
  contents: read          # Required for actions/checkout
  pull-requests: write    # Optional: for PR comments (future enhancement)

jobs:
  test:
    description: Run unit tests and browser tests across Node.js versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
      fail-fast: false

    inputs:
      node-version: "Matrix value (18 or 20)"

    steps:
      - name: Checkout repository
        action: actions/checkout@v4

      - name: Setup Node.js
        action: actions/setup-node@v4
        inputs:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        command: npm ci

      - name: Run tests
        command: npm test
        description: Executes both Node.js and browser tests

    outputs:
      test-result: "pass/fail (implicit via job status)"
      coverage-data: "Generated by npm test (not persisted)"

    success-criteria:
      - All unit tests pass
      - All browser tests pass in headless Chrome
      - No test timeouts or crashes

  lint:
    description: Run ESLint to check code quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        action: actions/checkout@v4

      - name: Setup Node.js
        action: actions/setup-node@v4
        inputs:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        command: npm ci

      - name: Run ESLint
        command: npm run lint

    outputs:
      lint-result: "pass/fail (implicit via job status)"

    success-criteria:
      - No ESLint errors
      - No ESLint warnings (if configured)

  typecheck:
    description: Run TypeScript type checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        action: actions/checkout@v4

      - name: Setup Node.js
        action: actions/setup-node@v4
        inputs:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        command: npm ci

      - name: Run TypeScript type check
        command: npm run check

    outputs:
      typecheck-result: "pass/fail (implicit via job status)"

    success-criteria:
      - No TypeScript type errors
      - All generated types are valid

  build:
    description: Validate production build process
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        action: actions/checkout@v4

      - name: Setup Node.js
        action: actions/setup-node@v4
        inputs:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        command: npm ci

      - name: Run production build
        command: npm run build
        description: Executes full build including TypeScript, bundling, and declarations

    outputs:
      build-result: "pass/fail (implicit via job status)"
      artifacts: "Build outputs (not persisted)"

    success-criteria:
      - Build completes without errors
      - All bundles are generated
      - Declaration files are created

workflow-outputs:
  overall-status: "pass/fail based on all jobs"
  test-results-node-18: "pass/fail from test job with node 18"
  test-results-node-20: "pass/fail from test job with node 20"
  lint-result: "pass/fail from lint job"
  typecheck-result: "pass/fail from typecheck job"
  build-result: "pass/fail from build job"

behavior:
  concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
    description: Cancel in-progress runs when new commits are pushed to the same PR

  parallelization:
    - All jobs run in parallel by default (no dependencies)
    - Matrix creates 2 parallel test jobs (Node 18 and 20)
    - Total parallelization: 4 jobs (test×2, lint, typecheck, build)

  failure-handling:
    - If any job fails, workflow is marked as failed
    - All jobs continue running (fail-fast: false on matrix)
    - PR cannot be merged if CI workflow fails (enforced by branch protection)

  caching:
    - npm dependencies cached via actions/setup-node
    - Cache key: hashFiles('**/package-lock.json')
    - Cache hit speeds up npm ci from ~15s to ~1s

integration:
  github-ui:
    - Status checks appear on PR page
    - Each job shows as separate check
    - Clicking check shows job logs
    - Re-run available for failed jobs

  branch-protection:
    - Workflow should be required status check
    - Prevents merging PRs with failing tests
    - Requires all jobs to pass

performance-targets:
  cold-run: "<10 minutes (no cache)"
  warm-run: "<5 minutes (with cache)"
  per-job: "<3 minutes average"

notes:
  - Workflow runs on both PRs and pushes to main for consistency
  - Uses existing npm scripts without modification
  - No artifacts are persisted (tests run fresh each time)
  - Browser tests use pre-installed Chrome on GitHub Actions runners
  - TypeScript compilation happens during npm ci (prepare script)
